services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - laravel
    db:
        image: postgres:15
        container_name: laravel-db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5431:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        ports:
            - "9999:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    redis:
        image: redis:latest
        container_name: laravel-redis
        ports:
            - "6375:6379"
        volumes:
            - redisdata:/data
        networks:
            - laravel

volumes:
    pgdata:
    redisdata:

networks:
    laravel:
